globalThis.EMOTES = [
    { category: "emotes", id: "kneel", label: "Kneel", scenario: "CODE_HUMAN_MEDIC_KNEEL" },
    { category: "emotes", id: "medic", label: "Medic", scenario: "CODE_HUMAN_MEDIC_TEND_TO_DEAD" },
    { category: "emotes", id: "traffic", label: "Traffic", scenario: "WORLD_HUMAN_CAR_PARK_ATTENDANT" },
    { category: "emotes", id: "binoculars", label: "Binoculars", scenario: "WORLD_HUMAN_BINOCULARS" },
    { category: "emotes", id: "bum", label: "Bum", scenario: "WORLD_HUMAN_BUM_FREEWAY" },
    { category: "emotes", id: "bumstand", label: "Bumstand", scenario: "WORLD_HUMAN_BUM_STANDING" },
    { category: "emotes", id: "wash", label: "Wash", scenario: "WORLD_HUMAN_BUM_WASH" },
    { category: "emotes", id: "cheer", label: "Cheer", scenario: "WORLD_HUMAN_CHEERING" },
    { category: "emotes", id: "drill", label: "Drill", scenario: "WORLD_HUMAN_CONST_DRILL" },
    { category: "emotes", id: "dealer", label: "Dealer", scenario: "WORLD_HUMAN_DRUG_DEALER" },
    { category: "emotes", id: "filmshocking", label: "Film Shocking", scenario: "WORLD_HUMAN_MOBILE_FILM_SHOCKING" },
    { category: "emotes", id: "leafblower", label: "Leaf Blower", scenario: "WORLD_HUMAN_GARDENER_LEAF_BLOWER" },
    { category: "emotes", id: "gardening", label: "Gardening", scenario: "WORLD_HUMAN_GARDENER_PLANT" },
    { category: "emotes", id: "guardpatrol", label: "Guard Patrol", scenario: "WORLD_HUMAN_GUARD_PATROL" },
    { category: "emotes", id: "hammering", label: "Hammering", scenario: "WORLD_HUMAN_HAMMERING" },
    { category: "emotes", id: "hangout", label: "Hangout", scenario: "WORLD_HUMAN_HANG_OUT_STREET" },
    { category: "emotes", id: "statue", label: "Statue", scenario: "WORLD_HUMAN_HUMAN_STATUE" },
    { category: "emotes", id: "janitor", label: "Janitor", scenario: "WORLD_HUMAN_JANITOR" },
    { category: "emotes", id: "jog", label: "Jog", scenario: "WORLD_HUMAN_JOG_STANDING" },
    { category: "emotes", id: "maid", label: "Maid", scenario: "WORLD_HUMAN_MAID_C" },
    { category: "emotes", id: "flex", label: "Flex", scenario: "WORLD_HUMAN_MUSCLE_FLEX" },
    { category: "emotes", id: "weights", label: "Weights", scenario: "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS" },
    { category: "emotes", id: "musician", label: "Musician", scenario: "WORLD_HUMAN_MUSICIAN" },
    { category: "emotes", id: "party", label: "Party", scenario: "WORLD_HUMAN_PARTYING" },
    { category: "emotes", id: "pushups", label: "Pushups", scenario: "WORLD_HUMAN_PUSH_UPS" },
    { category: "emotes", id: "shinetorch", label: "Shine Torch", scenario: "WORLD_HUMAN_SECURITY_SHINE_TORCH" },
    { category: "emotes", id: "weed", label: "Weed", scenario: "WORLD_HUMAN_SMOKING_POT" },
    { category: "emotes", id: "impatient", label: "Impatient", scenario: "WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT" },
    { category: "emotes", id: "map", label: "Map", scenario: "WORLD_HUMAN_TOURIST_MAP" },
    { category: "emotes", id: "mechanic", label: "Mechanic", scenario: "WORLD_HUMAN_VEHICLE_MECHANIC" },
    { category: "emotes", id: "welding", label: "Welding", scenario: "WORLD_HUMAN_WELDING" },
    { category: "emotes", id: "browse", label: "Browse", scenario: "WORLD_HUMAN_WINDOW_SHOP_BROWSE" },
    { category: "emotes", id: "yoga", label: "Yoga", scenario: "WORLD_HUMAN_YOGA" },
    { category: "emotes", id: "smoke", label: "Smoke", scenario: "WORLD_HUMAN_SMOKING", requiredItem: { itemId: "cigarette" } },
    { category: "emotes", id: "slump", label: "Slump", scenario: "WORLD_HUMAN_BUM_SLUMPED" },
    { category: "emotes", id: "cleanfront", label: "Clean Front", scenario: "WORLD_HUMAN_MAID_CLEAN" },
    { category: "emotes", id: "cheer1", label: "Cheer 1", dict: "anim@mp_player_intcelebrationpaired@f_f_backslap", anim: "backslap_right" },
    { category: "emotes", id: "cheer2", label: "Cheer 2", dict: "anim@mp_player_intcelebrationpaired@f_m_bro_hug", anim: "bro_hug_left" },
    { category: "emotes", id: "high5", label: "High 5", dict: "mp_ped_interaction", anim: "highfive_guy_a" },

    //Add Exit
    { category: "emotes", id: "arsepick", label: "Arse Pick", dict: "mp_player_int_upperarse_pick", anim: "mp_player_int_arse_pick", exit: "mp_player_int_arse_pick_exit" },
    { category: "emotes", id: "ballgrab", label: "Ball Grab", dict: "mp_player_int_uppergrab_crotch", anim: "mp_player_int_grab_crotch", exit: "mp_player_int_grab_crotch_exit" },
    { category: "emotes", id: "gangsign3", label: "Gang Sign 3", dict: "mp_player_int_upperbro_love", anim: "mp_player_int_bro_love", exit: "mp_player_int_bro_love_exit" },
    { category: "emotes", id: "fuckyou", label: "Fuck you", dict: "mp_player_int_upperv_sign", anim: "mp_player_int_v_sign", exit: "mp_player_int_v_sign_exit" },
    
    { category: "emotes", id: "holster", label: "Holster", dict: "reaction@intimidation@cop@unarmed", anim: "intro", duration: -1, flag: 50 },
    { category: "emotes", id: "notepad", label: "Notepad", dict: "amb@medic@standing@timeofdeath@base", anim: "base", prop: "notepad01", prop2: "pencil01" },
    { category: "emotes", id: "clipboard", label: "Clipboard", dict: "move_m@clipboard", anim: "idle", prop: "clipboard01" },
    { category: "emotes", id: "coffee", label: "Coffee", dict: "amb@world_human_drinking@coffee@male@idle_a", anim: "idle_c", prop: "coffee" },
    { category: "emotes", id: "phone", label: "Phone", dict: "cellphone@", anim: "cellphone_text_read_base", prop: "phone01" },
    { category: "emotes", id: "widephone", label: "Wide Phone", dict: "yoinks@musclephone", anim: "musclephone_clip", prop: "phone01" },
    { category: "emotes", id: "tennis", label: "Tennis", dict: "amb@world_human_tennis_player@male@base", anim: "base", prop: "tennis" },
    { category: "emotes", id: "stupor", label: "Stupor", dict: "amb@world_human_stupor@male_looking_right@base", anim: "base", flag: 1 },
    { category: "emotes", id: "piss", label: "Piss", dict: "missbigscore1switch_trevor_piss", anim: "piss_loop", flag: 9 },
    { category: "emotes", id: "shit", label: "Shit", dict: "missfbi3ig_0", anim: "shit_loop_trev", flag: 1 },
    { category: "emotes", id: "shower", label: "Shower", dict: "mp_safehouseshower@male@", anim: "male_shower_idle_a", flag: 9 },
    { category: "emotes", id: "lean", label: "Lean", dict: "amb@world_human_leaning@male@wall@back@legs_crossed@base", anim: "base", duration: -1, flag: 9 },
    { category: "emotes", id: "chinups", label: "Chinups", dict: "amb@prop_human_muscle_chin_ups@male@base", anim: "base", duration: -1, flag: 9 },
    { category: "emotes", id: "shrug3", label: "Shrug 3", dict: "oddjobs@bailbond_hobohang_out_street_b", anim: "idle_b", duration: -1, flag: 9 },
    { category: "emotes", id: "search", label: "Search", dict: "missexile3", anim: "ex03_dingy_search_case_a_michael", flag: 1 },
    { category: "emotes", id: "kneel3", label: "Kneel 3", dict: "oddjobs@hunter", anim: "idle_a", duration: 1, flag: 1 },
    { category: "emotes", id: "uncuff", label: "Uncuff", dict: "mp_arresting", anim: "a_uncuff", duration: 3000, flag: 16 },
    { category: "emotes", id: "trunk", label: "Trunk", dict: "fin_ext_p1-7", anim: "cs_devin_dual-7", flag: 1 },
    { category: "emotes", id: "lighter", label: "Lighter", dict: "cover@first_person@weapon@grenade", anim: "hi_l_cook", flag: 48 },
    { category: "emotes", id: "kickindoor", label: "Kick In Door", dict: "missprologuemcs_1", anim: "kick_down_player_zero", flag: 1 },
    { category: "emotes", id: "stretch5", label: "Stretch 5", dict: "switch@franklin@bed", anim: "stretch_short", flag: 48 },
    { category: "emotes", id: "pill", label: "Pill", dict: "mp_suicide", anim: "pill", duration: 2800, flag: 48 },
    { category: "emotes", id: "stretch2", label: "Stretch 2", dict: "switch@franklin@bed", anim: "stretch_long", flag: 48 },
    { category: "emotes", id: "getup", label: "Get up", dict: "switch@franklin@bed", anim: "sleep_getup_rubeyes", duration: -1, flag: 8 },
    { category: "emotes", id: "layspike", label: "Lay Spike", dict: "weapons@first_person@aim_rng@generic@projectile@thermal_charge@", anim: "plant_floor", duration: -1, flag: 48 },
    { category: "emotes", id: "layspike2", label: "Lay Spike 2", dict: "weapons@first_person@aim_rng@generic@projectile@thermal_charge@", anim: "plant_floor", duration: -1, flag: 0 },
    { category: "emotes", id: "hairtie", label: "Hair Tie", dict: "amb@code_human_wander_idles@female@idle_a", anim: "idle_a_hairtouch", duration: -1, flag: 48 },
    { category: "emotes", id: "veston", label: "Vest On", dict: "clothingtie", anim: "try_tie_positive_a", duration: -1, flag: 48 },
    { category: "emotes", id: "dab", label: "Dab", dict: "amb@world_human_statue@base", anim: "base", duration: -1, flag: 48 },
    { category: "emotes", id: "cokecut", label: "Coke cut", dict: "anim@amb@business@coc@coc_unpack_cut@", anim: "fullcut_cycle_v6_cokecutter", duration: -1, flag: 1 },
    { category: "emotes", id: "beg", label: "Beg", dict: "oddjobs@bailbond_mountain", anim: "excited_idle_b" },
    { category: "emotes", id: "searchground", label: "Search Ground", dict: "clothingshoes", anim: "try_shoes_positive_a" },
    { category: "emotes", id: "taxi", label: "Taxi", dict: "taxi_hail", anim: "hail_taxi", flag: 48 },
    { category: "emotes", id: "forgetit", label: "Forget It", dict: "taxi_hail", anim: "forget_it", flag: 48 },
    { category: "emotes", id: "cop", label: "Cop", dict: "amb@world_human_cop_idles@male@idle_a", anim: "idle_b", duration: -1, flag: 9 },
    { category: "emotes", id: "cross", label: "Cross", dict: "amb@world_human_hang_out_street@female_arms_crossed@base", anim: "base", duration: -1, flag: 9 },
    { category: "emotes", id: "cowerlow", label: "Cower Low", dict: "amb@code_human_cower@male@base", anim: "base", duration: -1, flag: 9 },
    { category: "emotes", id: "cower", label: "Cower", dict: "amb@code_human_cower_stand@male@base", anim: "base", duration: -1, flag: 32 },
    { category: "emotes", id: "cowerkneel", label: "Cower Kneel", dict: "random@homelandsecurity", anim: "knees_loop_girl", flag: 1 },
    { category: "emotes", id: "aware", label: "Aware", dict: "amb@code_human_cross_road@male@base", anim: "base", duration: -1, flag: 9 },
    { category: "emotes", id: "ballscratch", label: "Ball Scratch", dict: "amb@code_human_in_car_mp_actions@grab_crotch@std@ds@base", anim: "idle_a" },
    { category: "emotes", id: "lapdance1", label: "Lap Dance 1", dict: "mini@strip_club@lap_dance@ld_girl_a_song_a_p1", anim: "ld_girl_a_song_a_p1_f", flag: 32 },
    { category: "emotes", id: "dancef", label: "Dance F", dict: "anim@amb@nightclub@dancers@solomun_entourage@", anim: "mi_dance_facedj_17_v1_female^1", flag: 1 },
    { category: "emotes", id: "dancef2", label: "Dance F2", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim: "high_center", flag: 1 },
    { category: "emotes", id: "dancef3", label: "Dance F3", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim: "high_center_up", flag: 1 },
    { category: "emotes", id: "danceslow2", label: "Dances Low 2", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim: "low_center", flag: 1 },
    { category: "emotes", id: "danceslow3", label: "Dances Low 3", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim: "low_center_down", flag: 1 },
    { category: "emotes", id: "danceslow4", label: "Dances Low 4", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim: "low_center", flag: 1 },
    { category: "emotes", id: "dance", label: "Dance", dict: "anim@amb@nightclub@dancers@podium_dancers@", anim: "hi_dance_facedj_17_v2_male^5", flag: 1 },
    { category: "emotes", id: "dance2", label: "Dance 2", dict: "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim: "high_center_down", flag: 1 },
    { category: "emotes", id: "dance3", label: "Dance 3", dict: "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim: "high_center", flag: 1 },
    { category: "emotes", id: "dance3", label: "Dance 3", dict: "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim: "high_center", flag: 1 },
    { category: "emotes", id: "dance4", label: "Dance 4", dict: "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim: "high_center_up", flag: 1 },
    { category: "emotes", id: "danceupper", label: "Dance Upper", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim: "high_center", flag: 1 },
    { category: "emotes", id: "danceupper2", label: "Dance Upper 2", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim: "high_center_up", flag: 1 },
    { category: "emotes", id: "danceshy", label: "Dance Shy", dict: "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim: "low_center", flag: 1 },
    { category: "emotes", id: "danceshy2", label: "Dance Shy 2", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim: "low_center_down", flag: 1 },
    { category: "emotes", id: "danceslow", label: "Dance Slow", dict: "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim: "low_center", flag: 1 },
    { category: "emotes", id: "dancesilly9", label: "Dance Silly 9", dict: "rcmnigel1bnmt_1b", anim: "dance_loop_tyler", flag: 1 },
    { category: "emotes", id: "dance6", label: "Dance 6", dict: "misschinese2_crystalmazemcs1_cs", anim: "dance_loop_tao", flag: 1 },
    { category: "emotes", id: "dance7", label: "Dance 7", dict: "misschinese2_crystalmazemcs1_ig", anim: "dance_loop_tao", flag: 1 },
    { category: "emotes", id: "dance8", label: "Dance 8", dict: "missfbi3_sniping", anim: "dance_m_default", flag: 1 },
    { category: "emotes", id: "dance88", label: "Dance 88", dict: "missfbi3_sniping", anim: "dance_m_default", flag: 49 },
    { category: "emotes", id: "dancesilly", label: "Dance Silly", dict: "special_ped@mountain_dancer@monologue_3@monologue_3a", anim: "mnt_dnc_buttwag", flag: 1 },
    { category: "emotes", id: "dancesilly2", label: "Dance Silly 2", dict: "move_clown@p_m_zero_idles@", anim: "fidget_short_dance", flag: 1 },
    { category: "emotes", id: "dancesilly3", label: "Dance Silly 3", dict: "move_clown@p_m_two_idles@", anim: "fidget_short_dance", flag: 1 },
    { category: "emotes", id: "dancesilly4", label: "Dance Silly 4", dict: "anim@amb@nightclub@lazlow@hi_podium@", anim: "danceidle_hi_11_buttwiggle_b_laz", flag: 1 },
    { category: "emotes", id: "dancesilly5", label: "Dance Silly 5", dict: "timetable@tracy@ig_5@idle_a", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "dancesilly6", label: "Dance Silly 6", dict: "timetable@tracy@ig_8@idle_b", anim: "idle_d", flag: 1 },
    { category: "emotes", id: "dance9", label: "Dance 9", dict: "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim: "med_center_up", flag: 1 },
    { category: "emotes", id: "dancesilly8", label: "Dance Silly 8", dict: "anim@mp_player_intcelebrationfemale@the_woogie", anim: "the_woogie", flag: 1 },
    { category: "emotes", id: "dancesilly7", label: "Dance Silly 7", dict: "anim@amb@casino@mini@dance@dance_solo@female@var_b@", anim: "high_center", flag: 1 },
    { category: "emotes", id: "dance5", label: "Dance 5", dict: "anim@amb@casino@mini@dance@dance_solo@female@var_a@", anim: "med_center", flag: 1 },
    { category: "emotes", id: "danceglowstick", label: "Dance Glowstick", dict: "anim@amb@nightclub@lazlow@hi_railing@", anim: "ambclub_13_mi_hi_sexualgriding_laz", flag: 1, prop: "glowstickRight", prop2: "glowstickLeft" },
    { category: "emotes", id: "danceglowstick2", label: "Dance Glowstick 2", dict: "anim@amb@nightclub@lazlow@hi_railing@", anim: "ambclub_12_mi_hi_bootyshake_laz", flag: 1, prop: "glowstickRight", prop2: "glowstickLeft" },
    { category: "emotes", id: "danceglowstick3", label: "Dance Glowstick 3", dict: "anim@amb@nightclub@lazlow@hi_railing@", anim: "ambclub_09_mi_hi_bellydancer_laz", flag: 1, prop: "glowstickRight", prop2: "glowstickLeft" },
    { category: "emotes", id: "dancehorse", label: "Dance Horse", dict: "anim@amb@nightclub@lazlow@hi_dancefloor@", anim: "dancecrowd_li_15_handup_laz", flag: 1, prop: "toyHorse" },
    { category: "emotes", id: "dancehorse2", label: "Dance Horse 2", dict: "anim@amb@nightclub@lazlow@hi_dancefloor@", anim: "crowddance_hi_11_handup_laz", flag: 1, prop: "toyHorse" },
    { category: "emotes", id: "dancehorse3", label: "Dance Horse 3", dict: "anim@amb@nightclub@lazlow@hi_dancefloor@", anim: "dancecrowd_li_11_hu_shimmy_laz", flag: 1, prop: "toyHorse" },
    { category: "emotes", id: "conv1", label: "Conv 1", dict: "special_ped@jessie@monologue_5@monologue_5c", anim: "jessie_ig_1_p5_heressomthinginteresting_2" },
    { category: "emotes", id: "conv2", label: "Conv 2", dict: "special_ped@jessie@monologue_11@monologue_11c", anim: "jessie_ig_1_p11_canyouimagine_2" },
    { category: "emotes", id: "conv3", label: "Conv 3", dict: "rcmjosh4", anim: "beckon_a_cop_b" },
    { category: "emotes", id: "cross2", label: "Cross 2", dict: "rcmme_amanda1", anim: "stand_loop_cop" },
    { category: "emotes", id: "standguard3", label: "Stand Guard 3", dict: "yoinks@idlechill", anim: "yoinks_clip" },
    { category: "emotes", id: "investigate", label: "Investigate", dict: "amb@code_human_police_investigate@base", anim: "base" },
    { category: "emotes", id: "umbrella", label: "Umbrella", dict: "amb@code_human_wander_drinking@male@base", anim: "static", prop: "umbrella01" },
    { category: "emotes", id: "curse", label: "Curse", dict: "misscommon@response", anim: "curse" },
    { category: "emotes", id: "taunt", label: "Taunt", dict: "misscommon@response", anim: "threaten" },
    { category: "emotes", id: "what", label: "What", dict: "misscommon@response", anim: "numbnuts" },
    { category: "emotes", id: "break", label: "Break", dict: "misscommon@response", anim: "give_me_a_break" },
    { category: "emotes", id: "cmon", label: "Cmon", dict: "misscommon@response", anim: "bring_it_on" },
    { category: "emotes", id: "chair", label: "Chair", dict: "", anim: "", event: "animation:chair", disabled: true },
    { category: "emotes", id: "carry", label: "Carry", dict: "", anim: "", event: "animation:Carry" },
    { category: "emotes", id: "shoosh", label: "Shoosh", dict: "anim@mp_player_intuppershush", anim: "idle_a_fp", duration: 2000 },
    { category: "emotes", id: "picknose", label: "Pick Nose", dict: "anim@mp_player_intuppernose_pick", anim: "exit" },
    { category: "emotes", id: "wanker", label: "Wanker", dict: "anim@mp_player_intselfiewank", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "id", label: "ID", dict: "friends@laf@ig_5", anim: "nephew", flag: 48 },
    { category: "emotes", id: "why", label: "Why", dict: "gestures@m@standing@fat", anim: "gesture_why", flag: 48 },
    { category: "emotes", id: "hi", label: "Hi", dict: "gestures@m@standing@fat", anim: "gesture_hello", flag: 48 },
    { category: "emotes", id: "bye", label: "Bye", dict: "gestures@m@standing@fat", anim: "gesture_bye_soft", flag: 48 },
    { category: "emotes", id: "come", label: "Come", dict: "gestures@m@standing@fat", anim: "gesture_come_here_hard", flag: 48 },
    { category: "emotes", id: "down", label: "Down", dict: "gestures@m@standing@fat", anim: "gesture_hand_down", flag: 48 },
    { category: "emotes", id: "yes", label: "Yes", dict: "random@getawaydriver", anim: "gesture_nod_yes_hard", flag: 48 },
    { category: "emotes", id: "swatcome", label: "Swat Come", dict: "swat", anim: "come", flag: 48 },
    { category: "emotes", id: "swatfreeze", label: "Swat Freeze", dict: "swat", anim: "freeze", flag: 48 },
    { category: "emotes", id: "swatrally", label: "Swat Rally", dict: "swat", anim: "rally_point", flag: 48 },
    { category: "emotes", id: "swatyes", label: "Swat Yes", dict: "swat", anim: "understood", flag: 48 },
    { category: "emotes", id: "swatback", label: "Swat Back", dict: "swat", anim: "you_back", flag: 48 },
    { category: "emotes", id: "swatfwd", label: "Swat Forward", dict: "swat", anim: "you_fwd", flag: 48 },
    { category: "emotes", id: "swatleft", label: "Swat Left", dict: "swat", anim: "you_left", flag: 48 },
    { category: "emotes", id: "swatright", label: "Swat Right", dict: "swat", anim: "you_right", flag: 48 },
    { category: "emotes", id: "ziptied", label: "Ziptied", dict: "re@stag_do@idle_a", anim: "idle_a_ped", flag: 49 },
    { category: "emotes", id: "breakzipties", label: "Break Zipties", dict: "re@stag_do@idle_a", anim: "idle_c_ped", flag: 49 },
    { category: "emotes", id: "wavedown", label: "Wave Down", dict: "random@mugging5", anim: "001445_01_gangintimidation_1_female_idle_b", flag: 49 },
    { category: "emotes", id: "hitch", label: "Hitch", dict: "random@hitch_lift", anim: "idle_f", flag: 49 },
    { category: "emotes", id: "armwindow", label: "Arm Window", dict: "anim@veh@lowrider@std@ds@arm@base", anim: "sit_low_lowdoor", flag: 49 },
    { category: "emotes", id: "armwindow2", label: "Arm Window 2", dict: "anim@veh@armwindow", anim: "sit_low_lowdoor", flag: 49 },
    { category: "emotes", id: "armwindow3", label: "Arm Window 3", dict: "anim@veh@armwindow2", anim: "sit_low_lowdoor2", flag: 49 },
    { category: "emotes", id: "armwindow4", label: "Arm Window 4", dict: "anim@veh@armwindow3", anim: "sit_low_lowdoor3", flag: 49 },
    { category: "emotes", id: "handsup2", label: "Hands Up 2", dict: "missfbi5ig_22", anim: "hands_up_anxious_scientist", flag: 49 },
    { category: "emotes", id: "handsup3", label: "Hands Up 3", dict: "missfbi5ig_22", anim: "hands_up_loop_scientist", flag: 49 },
    { category: "emotes", id: "handshead", label: "Hands Head", dict: "random@arrests@busted", anim: "idle_a", flag: 2 },
    { category: "emotes", id: "handshead2", label: "Hands Head 2", dict: "random@arrests@busted", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "twerk", label: "Twerk", dict: "switch@trevor@mocks_lapdance", anim: "001443_01_trvs_28_idle_stripper", flag: 1 },
    { category: "emotes", id: "karate", label: "Karate", dict: "anim@mp_player_intcelebrationfemale@karate_chops", anim: "karate_chops", flag: 0 },
    { category: "emotes", id: "karate2", label: "Karate 2", dict: "anim@mp_player_intcelebrationmale@karate_chops", anim: "karate_chops", flag: 0 },
    { category: "emotes", id: "cprstanding", label: "CPR Standing", dict: "mini@cpr@char_a@cpr_str", anim: "cpr_pumpchest", flag: 31 },
    { category: "emotes", id: "suicidepill", label: "Suicide Pill", dict: "mp_suicide", anim: "pill", flag: 9 },
    { category: "emotes", id: "drink", label: "Drink", dict: "mp_player_inteat@pnq", anim: "loop", flag: 48 },
    { category: "emotes", id: "beast", label: "Beast", dict: "anim@mp_fm_event@intro", anim: "beast_transform", flag: 0 },
    { category: "emotes", id: "chill", label: "Chill", dict: "switch@trevor@scares_tramp", anim: "trev_scares_tramp_idle_tramp", flag: 1 },
    { category: "emotes", id: "cloudgaze", label: "Cloud Gaze", dict: "switch@trevor@annoys_sunbathers", anim: "trev_annoys_sunbathers_loop_girl", flag: 1 },
    { category: "emotes", id: "cloudgaze2", label: "Cloud Gaze 2", dict: "switch@trevor@annoys_sunbathers", anim: "trev_annoys_sunbathers_loop_guy", flag: 1 },
    { category: "emotes", id: "prone", label: "Prone", dict: "missfbi3_sniping", anim: "prone_dave", flag: 1 },
    { category: "emotes", id: "pullover", label: "Pullover", dict: "misscarsteal3pullover", anim: "pull_over_right", flag: 0 },
    { category: "emotes", id: "idle", label: "Idle", dict: "anim@heists@heist_corona@team_idles@male_a", anim: "idle", flag: 1 },
    { category: "emotes", id: "idle8", label: "Idle 8", dict: "amb@world_human_hang_out_street@male_b@idle_a", anim: "idle_b", flag: 1 },
    { category: "emotes", id: "idle9", label: "Idle 9", dict: "friends@fra@ig_1", anim: "base_idle", flag: 1 },
    { category: "emotes", id: "idle10", label: "Idle 10", dict: "mp_move@prostitute@m@french", anim: "idle", flag: 1 },
    { category: "emotes", id: "idle11", label: "Idle 11", dict: "random@countrysiderobbery", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "idle2", label: "Idle 2", dict: "anim@heists@heist_corona@team_idles@female_a", anim: "idle", flag: 1 },
    { category: "emotes", id: "idle3", label: "Idle 3", dict: "anim@heists@humane_labs@finale@strip_club", anim: "ped_b_celebrate_loop", flag: 1 },
    { category: "emotes", id: "idle4", label: "Idle 4", dict: "anim@mp_celebration@idles@female", anim: "celebration_idle_f_a", flag: 1 },
    { category: "emotes", id: "idle5", label: "Idle 5", dict: "anim@mp_corona_idles@female_b@idle_a", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "idle6", label: "Idle 6", dict: "anim@mp_corona_idles@male_c@idle_a", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "idle7", label: "Idle 7", dict: "anim@mp_corona_idles@male_d@idle_a", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "wait3", label: "Wait 3", dict: "amb@world_human_hang_out_street@female_hold_arm@idle_a", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "idledrunk", label: "Idle Drunk", dict: "random@drunk_driver_1", anim: "drunk_driver_stand_loop_dd1", flag: 1 },
    { category: "emotes", id: "idledrunk2", label: "Idle Drunk 2", dict: "random@drunk_driver_1", anim: "drunk_driver_stand_loop_dd2", flag: 1 },
    { category: "emotes", id: "idledrunk3", label: "Idle Drunk 3", dict: "missarmenian2", anim: "standing_idle_loop_drunk", flag: 1 },
    { category: "emotes", id: "airguitar", label: "Air Guitar", dict: "anim@mp_player_intcelebrationfemale@air_guitar", anim: "air_guitar", flag: 0 },
    { category: "emotes", id: "airsynth", label: "Air Synth", dict: "anim@mp_player_intcelebrationfemale@air_synth", anim: "air_synth", flag: 0 },
    { category: "emotes", id: "argue", label: "Argue", dict: "misscarsteal4@actor", anim: "actor_berating_loop", flag: 0 },
    { category: "emotes", id: "argue2", label: "Argue 2", dict: "oddjobs@assassinate@vice@hooker", anim: "argue_a", flag: 0 },
    { category: "emotes", id: "bartender", label: "Bartender", dict: "anim@amb@clubhouse@bar@drink@idle_a", anim: "idle_a_bartender", flag: 1 },
    { category: "emotes", id: "blowkiss", label: "Blow Kiss", dict: "anim@mp_player_intcelebrationfemale@blow_kiss", anim: "blow_kiss", flag: 0 },
    { category: "emotes", id: "blowkiss2", label: "Blow Kiss 2", dict: "anim@mp_player_intselfieblow_kiss", anim: "exit", flag: 48 },
    { category: "emotes", id: "curtsy", label: "Curtsy", dict: "anim@mp_player_intcelebrationpaired@f_f_sarcastic", anim: "sarcastic_left", flag: 0 },
    { category: "emotes", id: "comeatmebro", label: "Come At Me Bro", dict: "mini@triathlon", anim: "want_some_of_this", flag: 48 },
    { category: "emotes", id: "cop2", label: "Cop 2", dict: "anim@amb@nightclub@peds@", anim: "rcmme_amanda1_stand_loop_cop", flag: 1 },
    { category: "emotes", id: "cop3", label: "Cop 3", dict: "amb@code_human_police_investigate@idle_a", anim: "idle_b", flag: 1 },
    { category: "emotes", id: "standguard", label: "Stand Guard", dict: "amb@world_human_stand_guard@male@idle_a", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "standguard2", label: "Stand Guard 2", dict: "yoinks@idlechill", anim: "yoinks_clip", flag: 1 },
    { category: "emotes", id: "crossarms", label: "Cross Arms", dict: "amb@world_human_hang_out_street@female_arms_crossed@idle_a", anim: "idle_a", flag: 0 },
    { category: "emotes", id: "crossarms2", label: "Cross Arms 2", dict: "amb@world_human_hang_out_street@male_c@idle_a", anim: "idle_b", flag: 0 },
    { category: "emotes", id: "crossarms3", label: "Cross Arms 3", dict: "anim@heists@heist_corona@single_team", anim: "single_team_loop_boss", flag: 0 },
    { category: "emotes", id: "crossarms4", label: "Cross Arms 4", dict: "random@street_race", anim: "_car_b_lookout", flag: 0 },
    { category: "emotes", id: "crossarms5", label: "Cross Arms 5", dict: "anim@amb@nightclub@peds@", anim: "rcmme_amanda1_stand_loop_cop", flag: 0 },
    { category: "emotes", id: "crossarms6", label: "Cross Arms 6", dict: "random@shop_gunstore", anim: "_idle", flag: 0 },
    { category: "emotes", id: "crossarmsside", label: "Cross Arms Side", dict: "rcmnigel1a_band_groupies", anim: "base_m2", flag: 0 },
    { category: "emotes", id: "damn", label: "Damn", dict: "anim@am_hold_up@male", anim: "shoplift_mid", flag: 48 },
    { category: "emotes", id: "pointdown", label: "Point Down", dict: "gestures@f@standing@casual", anim: "gesture_hand_down", flag: 0 },
    { category: "emotes", id: "facepalm2", label: "Face Palm 2", dict: "anim@mp_player_intcelebrationfemale@face_palm", anim: "face_palm", flag: 48 },
    { category: "emotes", id: "facepalm", label: "Face Palm", dict: "random@car_thief@agitated@idle_a", anim: "agitated_idle_a", flag: 48 },
    { category: "emotes", id: "facepalm3", label: "Face Palm 3", dict: "missminuteman_1ig_2", anim: "tasered_2", flag: 48 },
    { category: "emotes", id: "facepalm4", label: "Face Palm 4", dict: "anim@mp_player_intupperface_palm", anim: "idle_a", flag: 48 },
    { category: "emotes", id: "fallover", label: "Fall Over", dict: "random@drunk_driver_1", anim: "drunk_fall_over", flag: 2 },
    { category: "emotes", id: "fallover2", label: "Fall Over 2", dict: "mp_suicide", anim: "pistol", flag: 2 },
    { category: "emotes", id: "fallover3", label: "Fall Over 3", dict: "friends@frf@ig_2", anim: "knockout_plyr", flag: 2 },
    { category: "emotes", id: "fallover4", label: "Fall Over 4", dict: "anim@gangops@hostage@", anim: "victim_fail", flag: 2 },
    { category: "emotes", id: "fallasleep", label: "Fall Asleep", dict: "mp_sleep", anim: "sleep_loop", flag: 63 },
    { category: "emotes", id: "fightme", label: "Fight Me", dict: "anim@deathmatch_intros@unarmed", anim: "intro_male_unarmed_c", flag: 0 },
    { category: "emotes", id: "fightme2", label: "Fight Me 2", dict: "anim@deathmatch_intros@unarmed", anim: "intro_male_unarmed_e", flag: 48 },
    { category: "emotes", id: "finger", label: "Finger", dict: "anim@mp_player_intselfiethe_bird", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "finger2", label: "Finger 2", dict: "anim@mp_player_intupperfinger", anim: "idle_a_fp", flag: 49 },
    { category: "emotes", id: "smokemale", label: "Smoke Male", dict: "amb@world_human_smoking@male@male_a@base", anim: "base", flag: 49, prop: "cigarette", requiredItem: { itemId: "cigarette" } },
    { category: "emotes", id: "smokefemale", label: "Smoke Female", dict: "amb@world_human_smoking@female@idle_a", anim: "idle_b", flag: 49, prop: "cigarette", requiredItem: { itemId: "cigarette" } },
    { category: "emotes", id: "cigarette", label: "Cigarette", dict: "amb@world_human_smoking@male@male_a@enter", anim: "enter", flag: 0, prop: "cigmouth", requiredItem: { itemId: "cigarette" } },
    { category: "emotes", id: "cigar", label: "Cigar", dict: "amb@world_human_smoking@male@male_a@enter", anim: "enter", flag: 0, prop: "cigar1", requiredItem: { itemId: "cigarette", variant: "cigar" } },
    { category: "emotes", id: "cigar2", label: "Cigar 2", dict: "amb@world_human_smoking@male@male_a@enter", anim: "enter", flag: 0, prop: "cigar2", requiredItem: { itemId: "cigarette", variant: "cigar" } },
    { category: "emotes", id: "cigar3", label: "Cigar 3", dict: "amb@world_human_smoking@male@male_a@enter", anim: "enter", flag: 0, prop: "cigar3", requiredItem: { itemId: "cigarette", variant: "cigar" } },
    { category: "emotes", id: "handshake", label: "Handshake", dict: "mp_ped_interaction", anim: "handshake_guy_a", flag: 0 },
    { category: "emotes", id: "handshake2", label: "Handshake 2", dict: "mp_ped_interaction", anim: "handshake_guy_b", flag: 0 },
    { category: "emotes", id: "wait4", label: "Wait 4", dict: "amb@world_human_hang_out_street@Female_arm_side@idle_a", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "wait5", label: "Wait 5", dict: "missclothing", anim: "idle_storeclerk", flag: 49 },
    { category: "emotes", id: "wait6", label: "Wait 6", dict: "timetable@amanda@ig_2", anim: "ig_2_base_amanda", flag: 49 },
    { category: "emotes", id: "wait7", label: "Wait 7", dict: "rcmnigel1cnmt_1c", anim: "base", flag: 49 },
    { category: "emotes", id: "wait8", label: "Wait 8", dict: "rcmjosh1", anim: "idle", flag: 49 },
    { category: "emotes", id: "wait9", label: "Wait 9", dict: "rcmjosh2", anim: "josh_2_intp1_base", flag: 49 },
    { category: "emotes", id: "wait10", label: "Wait 10", dict: "timetable@amanda@ig_3", anim: "ig_3_base_tracy", flag: 49 },
    { category: "emotes", id: "wait11", label: "Wait 11", dict: "misshair_shop@hair_dressers", anim: "keeper_base", flag: 49 },
    { category: "emotes", id: "hiking", label: "Hiking", dict: "move_m@hiking", anim: "idle", flag: 49 },
    { category: "emotes", id: "hug", label: "Hug", dict: "mp_ped_interaction", anim: "kisses_guy_a", flag: 0 },
    { category: "emotes", id: "hug2", label: "Hug 2", dict: "mp_ped_interaction", anim: "kisses_guy_b", flag: 0 },
    { category: "emotes", id: "hug3", label: "Hug 3", dict: "mp_ped_interaction", anim: "hugs_guy_a", flag: 0 },
    { category: "emotes", id: "inspect", label: "Inspect", dict: "random@train_tracks", anim: "idle_e", flag: 0 },
    { category: "emotes", id: "jazzhands", label: "Jazz Hands", dict: "anim@mp_player_intcelebrationfemale@jazz_hands", anim: "jazz_hands", flag: 0 },
    { category: "emotes", id: "jog2", label: "Jog 2", dict: "amb@world_human_jog_standing@male@idle_a", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "jog3", label: "Jog 3", dict: "amb@world_human_jog_standing@female@idle_a", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "jog4", label: "Jog 4", dict: "amb@world_human_power_walker@female@idle_a", anim: "idle_a", flag: 47 },
    { category: "emotes", id: "jog5", label: "Jog 5", dict: "move_m@joy@a", anim: "walk", flag: 47 },
    { category: "emotes", id: "jumpingjacks", label: "Jumping Jacks", dict: "timetable@reunited@ig_2", anim: "jimmy_getknocked", flag: 0 },
    { category: "emotes", id: "kneel2", label: "Kneel 2", dict: "rcmextreme3", anim: "idle", flag: 1 },
    { category: "emotes", id: "kneel3", label: "Kneel 3", dict: "amb@world_human_bum_wash@male@low@idle_a", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "kneel4", label: "Kneel 4", dict: "amb@medic@standing@tendtodead@base", anim: "base", flag: 1 },
    { category: "emotes", id: "knock", label: "Knock", dict: "timetable@jimmy@doorknock@", anim: "knockdoor_idle", flag: 1 },
    { category: "emotes", id: "knock2", label: "Knock 2", dict: "missheistfbi3b_ig7", anim: "lift_fibagent_loop", flag: 1 },
    { category: "emotes", id: "knucklecrunch", label: "Knuckle Crunch", dict: "anim@mp_player_intcelebrationfemale@knuckle_crunch", anim: "knuckle_crunch", flag: 48 },
    { category: "emotes", id: "lapdance", label: "Lap Dance", dict: "mp_safehouse", anim: "lap_dance_girl", flag: 1 },
    { category: "emotes", id: "lean2", label: "Lean 2", dict: "amb@world_human_leaning@female@wall@back@hand_up@idle_a", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "lean3", label: "Lean 3", dict: "amb@world_human_leaning@female@wall@back@holding_elbow@idle_a", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "lean4", label: "Lean 4", dict: "amb@world_human_leaning@male@wall@back@foot_up@idle_a", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "lean5", label: "Lean 5", dict: "amb@world_human_leaning@male@wall@back@hands_together@idle_b", anim: "idle_b", flag: 1 },
    { category: "emotes", id: "leanflirt", label: "Lean Flirt", dict: "random@street_race", anim: "_car_a_flirt_girl", flag: 1 },
    { category: "emotes", id: "leanbar2", label: "Lean Bar 2", dict: "amb@prop_human_bum_shopping_cart@male@idle_a", anim: "idle_c", flag: 1 },
    { category: "emotes", id: "leanbar3", label: "Lean Bar 3", dict: "anim@amb@nightclub@lazlow@ig1_vip@", anim: "clubvip_base_laz", flag: 1 },
    { category: "emotes", id: "leanbar4", label: "Lean Bar 4", dict: "anim@heists@prison_heist", anim: "ped_b_loop_a", flag: 1 },
    { category: "emotes", id: "leanhigh", label: "Lean High", dict: "anim@mp_ferris_wheel", anim: "idle_a_player_one", flag: 1 },
    { category: "emotes", id: "leanhigh2", label: "Lean High 2", dict: "anim@mp_ferris_wheel", anim: "idle_a_player_two", flag: 1 },
    { category: "emotes", id: "leanside", label: "Lean Side", dict: "timetable@mime@01_gc", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "leanside2", label: "Lean Side 2", dict: "misscarstealfinale", anim: "packer_idle_1_trevor", flag: 1 },
    { category: "emotes", id: "leanside3", label: "Lean Side 3", dict: "misscarstealfinalecar_5_ig_1", anim: "waitloop_lamar", flag: 1 },
    { category: "emotes", id: "leanside4", label: "Lean Side 4", dict: "misscarstealfinalecar_5_ig_1", anim: "waitloop_lamar", flag: 1 },
    { category: "emotes", id: "leanside5", label: "Lean Side 5", dict: "rcmjosh2", anim: "josh_2_intp1_base", flag: 1 },
    { category: "emotes", id: "me", label: "Me", dict: "gestures@f@standing@casual", anim: "gesture_me_hard", flag: 48 },
    { category: "emotes", id: "mechanic", label: "Mechanic", dict: "mini@repair", anim: "fixing_a_ped", flag: 1 },
    { category: "emotes", id: "mechanic2", label: "Mechanic 2", dict: "amb@world_human_vehicle_mechanic@male@base", anim: "idle_a", flag: 0 },
    { category: "emotes", id: "mechanic3", label: "Mechanic 3", dict: "anim@amb@clubhouse@tutorial@bkr_tut_ig3@", anim: "machinic_loop_mechandplayer", flag: 0 },
    { category: "emotes", id: "mechanic4", label: "Mechanic 4", dict: "anim@amb@clubhouse@tutorial@bkr_tut_ig3@", anim: "machinic_loop_mechandplayer", flag: 0 },
    { category: "emotes", id: "medic2", label: "Medic 2", dict: "amb@medic@standing@tendtodead@base", anim: "base", flag: 0 },
    { category: "emotes", id: "meditate", label: "Meditate", dict: "rcmcollect_paperleadinout@", anim: "meditiate_idle", flag: 1 },
    { category: "emotes", id: "meditate2", label: "Meditate 2", dict: "rcmepsilonism3", anim: "ep_3_rcm_marnie_meditating", flag: 1 },
    { category: "emotes", id: "meditate3", label: "Meditate 3", dict: "rcmepsilonism3", anim: "base_loop", flag: 1 },
    { category: "emotes", id: "trooperpushup", label: "Trooper Pushup", dict: "yoinks@1armpushup", anim: "onearmpushup_clip", flag: 1 },
    { category: "emotes", id: "metal", label: "Metal", dict: "anim@mp_player_intincarrockstd@ps@", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "no", label: "No", dict: "anim@heists@ornate_bank@chat_manager", anim: "fail", flag: 48 },
    { category: "emotes", id: "no2", label: "No 2", dict: "mp_player_int_upper_nod", anim: "mp_player_int_nod_no", flag: 49 },
    { category: "emotes", id: "nosepick", label: "Nose Pick", dict: "anim@mp_player_intcelebrationfemale@nose_pick", anim: "nose_pick", flag: 48 },
    { category: "emotes", id: "noway", label: "No Way", dict: "gestures@m@standing@casual", anim: "gesture_no_way", flag: 48 },
    { category: "emotes", id: "ok", label: "OK", dict: "anim@mp_player_intselfiedock", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "outofbreath", label: "Out of Breath", dict: "re@construction", anim: "out_of_breath", flag: 0 },
    { category: "emotes", id: "pickup", label: "Pick Up", dict: "random@domestic", anim: "pickup_low", flag: 0 },
    { category: "emotes", id: "push", label: "Push", dict: "missfinale_c2ig_11", anim: "pushcar_offcliff_f", flag: 49 },
    { category: "emotes", id: "push2", label: "Push 2", dict: "missfinale_c2ig_11", anim: "pushcar_offcliff_m", flag: 49 },
    { category: "emotes", id: "point", label: "Point", dict: "gestures@f@standing@casual", anim: "gesture_point", flag: 0 },
    { category: "emotes", id: "countdown", label: "Countdown", dict: "random@street_race", anim: "grid_girl_race_start", flag: 0 },
    { category: "emotes", id: "pointright", label: "Point Right", dict: "mp_gun_shop_tut", anim: "indicate_right", flag: 0 },
    { category: "emotes", id: "salute", label: "Salute", dict: "anim@mp_player_intincarsalutestd@ds@", anim: "idle_a", flag: 48 },
    { category: "emotes", id: "salute2", label: "Salute 2", dict: "anim@mp_player_intincarsalutestd@ps@", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "salute3", label: "Salute 3", dict: "anim@mp_player_intuppersalute", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "scared", label: "Scared", dict: "random@domestic", anim: "f_distressed_loop", flag: 49 },
    { category: "emotes", id: "scared2", label: "Scared 2", dict: "random@homelandsecurity", anim: "knees_loop_girl", flag: 1 },
    { category: "emotes", id: "screwyou", label: "Screw You", dict: "misscommon@response", anim: "screw_you", flag: 0 },
    { category: "emotes", id: "shakeoff", label: "Shake Off", dict: "move_m@_idles@shake_off", anim: "shakeoff_1", flag: 48 },
    { category: "emotes", id: "shot", label: "Shot", dict: "random@crash_rescue@wounded@base", anim: "base", flag: 1 },
    { category: "emotes", id: "sleep", label: "Sleep", dict: "timetable@tracy@sleep@", anim: "idle_c", flag: 1 },
    { category: "emotes", id: "shrug", label: "Shrug", dict: "gestures@f@standing@casual", anim: "gesture_shrug_hard", flag: 0 },
    { category: "emotes", id: "shrug2", label: "Shrug 2", dict: "gestures@m@standing@casual", anim: "gesture_shrug_hard", flag: 0 },
    { category: "emotes", id: "sit", label: "Sit", dict: "anim@amb@business@bgen@bgen_no_work@", anim: "sit_phone_phoneputdown_idle_nowork", flag: 1 },
    { category: "emotes", id: "sit2", label: "Sit 2", dict: "rcm_barry3", anim: "barry_3_sit_loop", flag: 1 },
    { category: "emotes", id: "sit3", label: "Sit 3", dict: "amb@world_human_picnic@male@idle_a", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "sit4", label: "Sit 4", dict: "amb@world_human_picnic@female@idle_a", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "sit5", label: "Sit 5", dict: "anim@heists@fleeca_bank@ig_7_jetski_owner", anim: "owner_idle", flag: 1 },
    { category: "emotes", id: "sit6", label: "Sit 6", dict: "timetable@jimmy@mics3_ig_15@", anim: "idle_a_jimmy", flag: 1 },
    { category: "emotes", id: "sit7", label: "Sit 7", dict: "anim@amb@nightclub@lazlow@lo_alone@", anim: "lowalone_base_laz", flag: 1 },
    { category: "emotes", id: "sit8", label: "Sit 8", dict: "timetable@jimmy@mics3_ig_15@", anim: "mics3_15_base_jimmy", flag: 1 },
    { category: "emotes", id: "sit9", label: "Sit 9", dict: "amb@world_human_stupor@male@idle_a", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "sitlean", label: "Sit Lean", dict: "timetable@tracy@ig_14@", anim: "ig_14_base_tracy", flag: 1 },
    { category: "emotes", id: "sitsad", label: "Sit Sad", dict: "anim@amb@business@bgen@bgen_no_work@", anim: "sit_phone_phoneputdown_sleeping-noworkfemale", flag: 1 },
    { category: "emotes", id: "sitscared", label: "Sit Scared", dict: "anim@heists@ornate_bank@hostages@hit", anim: "hit_loop_ped_b", flag: 1 },
    { category: "emotes", id: "sitscared2", label: "Sit Scared 2", dict: "anim@heists@ornate_bank@hostages@ped_c@", anim: "flinch_loop", flag: 1 },
    { category: "emotes", id: "sitscared3", label: "Sit Scared 3", dict: "anim@heists@ornate_bank@hostages@ped_e@", anim: "flinch_loop", flag: 1 },
    { category: "emotes", id: "sitdrunk", label: "Sit Drunk", dict: "timetable@amanda@drunk@base", anim: "base", flag: 1 },
    { category: "emotes", id: "sitchair2", label: "Sit Chair 2", dict: "timetable@ron@ig_5_p3", anim: "ig_5_p3_base", flag: 1 },
    { category: "emotes", id: "sitchair3", label: "Sit Chair 3", dict: "timetable@reunited@ig_10", anim: "base_amanda", flag: 1 },
    { category: "emotes", id: "sitchair4", label: "Sit Chair 4", dict: "timetable@ron@ig_3_couch", anim: "base", flag: 1 },
    { category: "emotes", id: "sitchair5", label: "Sit Chair 5", dict: "timetable@jimmy@mics3_ig_15@", anim: "mics3_15_base_tracy", flag: 1 },
    { category: "emotes", id: "sitchair6", label: "Sit Chair 6", dict: "timetable@maid@couch@", anim: "base", flag: 1 },
    { category: "emotes", id: "sitchairside", label: "Sit Chair Side", dict: "timetable@ron@ron_ig_2_alt1", anim: "ig_2_alt1_base", flag: 1 },
    { category: "emotes", id: "clapangry", label: "Clap Angry", dict: "anim@arena@celeb@flat@solo@no_props@", anim: "angry_clap_a_player_a", flag: 1 },
    { category: "emotes", id: "slowclap3", label: "Slow Clap 3", dict: "anim@mp_player_intupperslow_clap", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "clap", label: "Clap", dict: "amb@world_human_cheering@male_a", anim: "base", flag: 49 },
    { category: "emotes", id: "slowclap", label: "Slow Clap", dict: "anim@mp_player_intcelebrationfemale@slow_clap", anim: "slow_clap", flag: 49 },
    { category: "emotes", id: "slowclap2", label: "Slow Clap 2", dict: "anim@mp_player_intcelebrationmale@slow_clap", anim: "slow_clap", flag: 49 },
    { category: "emotes", id: "smell", label: "Smell", dict: "move_p_m_two_idles@generic", anim: "fidget_sniff_fingers", flag: 48 },
    { category: "emotes", id: "stickup", label: "Stick Up", dict: "random@countryside_gang_fight", anim: "biker_02_stickup_loop", flag: 1 },
    { category: "emotes", id: "stickup2", label: "Stick Up 2", dict: "random@countryside_gang_fight", anim: "biker_02_stickup_loop", flag: 49 },
    { category: "emotes", id: "stumble", label: "Stumble", dict: "misscarsteal4@actor", anim: "stumble", flag: 0 },
    { category: "emotes", id: "stunned", label: "Stunned", dict: "stungun@standing", anim: "damage", flag: 0 },
    { category: "emotes", id: "sunbathe", label: "Sunbathe", dict: "amb@world_human_sunbathe@male@back@base", anim: "base", flag: 1 },
    { category: "emotes", id: "sunbathe2", label: "Sunbathe 2", dict: "amb@world_human_sunbathe@female@back@base", anim: "base", flag: 1 },
    { category: "emotes", id: "t", label: "T", dict: "missfam5_yoga", anim: "a2_pose", flag: 1 },
    { category: "emotes", id: "t2", label: "T 2", dict: "missfam5_yoga", anim: "a2_pose", flag: 49 },
    { category: "emotes", id: "think5", label: "Think 5", dict: "mp_cp_welcome_tutthink", anim: "b_think", flag: 49 },
    { category: "emotes", id: "think", label: "Think", dict: "misscarsteal4@aliens", anim: "rehearsal_base_idle_director", flag: 49 },
    { category: "emotes", id: "think3", label: "Think 3", dict: "timetable@tracy@ig_8@base", anim: "base", flag: 49 },
    { category: "emotes", id: "think2", label: "Think 2", dict: "missheist_jewelleadinout", anim: "jh_int_outro_loop_a", flag: 49 },
    { category: "emotes", id: "thumbsup3", label: "Thumbs Up 3", dict: "anim@mp_player_intincarthumbs_uplow@ds@", anim: "enter", flag: 49 },
    { category: "emotes", id: "thumbsup2", label: "Thumbs Up 2", dict: "anim@mp_player_intselfiethumbs_up", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "thumbsup", label: "Thumbs Up", dict: "anim@mp_player_intupperthumbs_up", anim: "idle_a", flag: 48 },
    { category: "emotes", id: "type", label: "Type", dict: "anim@heists@prison_heiststation@cop_reactions", anim: "cop_b_idle", flag: 1 },
    { category: "emotes", id: "type2", label: "Type 2", dict: "anim@heists@prison_heistig1_p1_guard_checks_bus", anim: "loop", flag: 1 },
    { category: "emotes", id: "type3", label: "Type 3", dict: "mp_prison_break", anim: "hack_loop", flag: 1 },
    { category: "emotes", id: "type4", label: "Type 4", dict: "mp_fbi_heist", anim: "loop", flag: 1 },
    { category: "emotes", id: "warmth", label: "Warmth", dict: "amb@world_human_stand_fire@male@idle_a", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "wave4", label: "Wave 4", dict: "random@mugging5", anim: "001445_01_gangintimidation_1_female_idle_b", flag: 49 },
    { category: "emotes", id: "wave2", label: "Wave 2", dict: "anim@mp_player_intcelebrationfemale@wave", anim: "wave", flag: 49 },
    { category: "emotes", id: "wave3", label: "Wave 3", dict: "friends@fra@ig_1", anim: "over_here_idle_a", flag: 49 },
    { category: "emotes", id: "wave", label: "Wave", dict: "friends@frj@ig_1", anim: "wave_a", flag: 49 },
    { category: "emotes", id: "wave5", label: "Wave 5", dict: "friends@frj@ig_1", anim: "wave_b", flag: 49 },
    { category: "emotes", id: "wave6", label: "Wave 6", dict: "friends@frj@ig_1", anim: "wave_c", flag: 49 },
    { category: "emotes", id: "wave7", label: "Wave 7", dict: "friends@frj@ig_1", anim: "wave_d", flag: 49 },
    { category: "emotes", id: "wave8", label: "Wave 8", dict: "friends@frj@ig_1", anim: "wave_e", flag: 49 },
    { category: "emotes", id: "wave9", label: "Wave 9", dict: "gestures@m@standing@casual", anim: "gesture_hello", flag: 49 },
    { category: "emotes", id: "whistle", label: "Whistle", dict: "taxi_hail", anim: "hail_taxi", flag: 49 },
    { category: "emotes", id: "whistle2", label: "Whistle 2", dict: "rcmnigel1c", anim: "hailing_whistle_waive_a", flag: 49 },
    { category: "emotes", id: "yeah", label: "Yeah", dict: "anim@mp_player_intupperair_shagging", anim: "idle_a", flag: 48 },
    { category: "emotes", id: "lift", label: "Lift", dict: "random@hitch_lift", anim: "idle_f", flag: 0 },
    { category: "emotes", id: "lol", label: "LOL", dict: "anim@arena@celeb@flat@paired@no_props@", anim: "laugh_a_player_b", flag: 0 },
    { category: "emotes", id: "lol2", label: "LOL 2", dict: "anim@arena@celeb@flat@solo@no_props@", anim: "giggle_a_player_b", flag: 0 },
    { category: "emotes", id: "statue2", label: "Statue 2", dict: "fra_0_int-1", anim: "cs_lamardavis_dual-1", flag: 17 },
    { category: "emotes", id: "statue3", label: "Statue 3", dict: "club_intro2-0", anim: "csb_englishdave_dual-0", flag: 1 },
    { category: "emotes", id: "gangsign", label: "Gang Sign", dict: "mp_player_int_uppergang_sign_a", anim: "mp_player_int_gang_sign_a", flag: 49 },
    { category: "emotes", id: "gangsign2", label: "Gang Sign 2", dict: "mp_player_int_uppergang_sign_b", anim: "mp_player_int_gang_sign_b", flag: 49 },
    { category: "emotes", id: "passout", label: "Pass Out", dict: "missarmenian2", anim: "drunk_loop", flag: 1 },
    { category: "emotes", id: "passout2", label: "Pass Out 2", dict: "missarmenian2", anim: "corpse_search_exit_ped", flag: 1 },
    { category: "emotes", id: "passout3", label: "Pass Out 3", dict: "anim@gangops@morgue@table@", anim: "body_search", flag: 1 },
    { category: "emotes", id: "passout4", label: "Pass Out 4", dict: "mini@cpr@char_b@cpr_def", anim: "cpr_pumpchest_idle", flag: 1 },
    { category: "emotes", id: "passout5", label: "Pass Out 5", dict: "random@mugging4", anim: "flee_backward_loop_shopkeeper", flag: 1 },
    { category: "emotes", id: "petting", label: "Petting", dict: "creatures@rottweiler@tricks@", anim: "petting_franklin", flag: 0 },
    { category: "emotes", id: "crawl", label: "Crawl", dict: "move_injured_ground", anim: "front_loop", flag: 33 },
    { category: "emotes", id: "flip2", label: "Flip 2", dict: "anim@arena@celeb@flat@solo@no_props@", anim: "cap_a_player_a", flag: 0 },
    { category: "emotes", id: "flip", label: "Flip", dict: "anim@arena@celeb@flat@solo@no_props@", anim: "flip_a_player_a", flag: 0 },
    { category: "emotes", id: "slide", label: "Slide", dict: "anim@arena@celeb@flat@solo@no_props@", anim: "slide_a_player_a", flag: 0 },
    { category: "emotes", id: "slide2", label: "Slide 2", dict: "anim@arena@celeb@flat@solo@no_props@", anim: "slide_b_player_a", flag: 0 },
    { category: "emotes", id: "slide3", label: "Slide 3", dict: "anim@arena@celeb@flat@solo@no_props@", anim: "slide_c_player_a", flag: 0 },
    { category: "emotes", id: "slugger", label: "Slugger", dict: "anim@arena@celeb@flat@solo@no_props@", anim: "slugger_a_player_a", flag: 0 },
    { category: "emotes", id: "flipoff", label: "Flip Off", dict: "anim@arena@celeb@podium@no_prop@", anim: "flip_off_a_1st", flag: 0 },
    { category: "emotes", id: "flipoff2", label: "Flip Off 2", dict: "anim@arena@celeb@podium@no_prop@", anim: "flip_off_c_1st", flag: 0 },
    { category: "emotes", id: "bow", label: "Bow", dict: "anim@arena@celeb@podium@no_prop@", anim: "regal_c_1st", flag: 0 },
    { category: "emotes", id: "bow2", label: "Bow 2", dict: "anim@arena@celeb@podium@no_prop@", anim: "regal_a_1st", flag: 0 },
    { category: "emotes", id: "keyfob", label: "Key Fob", dict: "anim@mp_player_intmenu@key_fob@", anim: "fob_click", flag: 0 },
    { category: "emotes", id: "golfswing", label: "Golf Swing", dict: "rcmnigel1d", anim: "swing_a_mark", flag: 0 },
    { category: "emotes", id: "eat", label: "Eat", dict: "mp_player_inteat@burger", anim: "mp_player_int_eat_burger", flag: 49 },
    { category: "emotes", id: "reaching", label: "Reaching", dict: "move_m@intimidation@cop@unarmed", anim: "idle", flag: 49 },
    { category: "emotes", id: "wait", label: "Wait", dict: "random@shop_tattoo", anim: "_idle_a", flag: 49 },
    { category: "emotes", id: "wait2", label: "Wait 2", dict: "missbigscore2aig_3", anim: "wait_for_van_c", flag: 49 },
    { category: "emotes", id: "wait12", label: "Wait 12", dict: "rcmjosh1", anim: "idle", flag: 49 },
    { category: "emotes", id: "wait13", label: "Wait 13", dict: "rcmnigel1a", anim: "base", flag: 49 },
    { category: "emotes", id: "lapdance2", label: "Lap Dance 2", dict: "mini@strip_club@private_dance@idle", anim: "priv_dance_idle", flag: 0 },
    { category: "emotes", id: "lapdance3", label: "Lap Dance 3", dict: "mini@strip_club@private_dance@part2", anim: "priv_dance_p2", flag: 0 },
    { category: "emotes", id: "slap", label: "Slap", dict: "melee@unarmed@streamed_variations", anim: "plyr_takedown_front_slap", flag: 0 },
    { category: "emotes", id: "headbutt", label: "Headbutt", dict: "melee@unarmed@streamed_variations", anim: "plyr_takedown_front_headbutt", flag: 0 },
    { category: "emotes", id: "fishdance", label: "Fish Dance", dict: "anim@mp_player_intupperfind_the_fish", anim: "idle_a", flag: 1 },
    { category: "emotes", id: "peace", label: "Peace", dict: "mp_player_int_upperpeace_sign", anim: "mp_player_int_peace_sign", flag: 49 },
    { category: "emotes", id: "peace2", label: "Peace 2", dict: "anim@mp_player_intupperpeace", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "cpr", label: "CPR", dict: "mini@cpr@char_a@cpr_str", anim: "cpr_pumpchest", flag: 1 },
    { category: "emotes", id: "ledge", label: "Ledge", dict: "missfbi1", anim: "ledge_loop", flag: 1 },
    { category: "emotes", id: "airplane", label: "Airplane", dict: "missfbi1", anim: "ledge_loop", flag: 49 },
    { category: "emotes", id: "peek", label: "Peek", dict: "random@paparazzi@peek", anim: "left_peek_a", flag: 1 },
    { category: "emotes", id: "cough", label: "Cough", dict: "timetable@gardener@smoking_joint", anim: "idle_cough", flag: 0 },
    { category: "emotes", id: "stretch", label: "Stretch", dict: "mini@triathlon", anim: "idle_e", flag: 0 },
    { category: "emotes", id: "stretch2", label: "Stretch 2", dict: "mini@triathlon", anim: "idle_f", flag: 0 },
    { category: "emotes", id: "stretch3", label: "Stretch 3", dict: "mini@triathlon", anim: "idle_d", flag: 0 },
    { category: "emotes", id: "stretch4", label: "Stretch 4", dict: "rcmfanatic1maryann_stretchidle_b", anim: "idle_e", flag: 0 },
    { category: "emotes", id: "celebrate", label: "Celebrate", dict: "rcmfanatic1celebrate", anim: "celebrate", flag: 0 },
    { category: "emotes", id: "punching", label: "Punching", dict: "rcmextreme2", anim: "loop_punching", flag: 62 },
    { category: "emotes", id: "superhero", label: "Superhero", dict: "rcmbarry", anim: "base", flag: 1 },
    { category: "emotes", id: "superhero2", label: "Superhero 2", dict: "rcmbarry", anim: "base", flag: 49 },
    { category: "emotes", id: "mindcontrol", label: "Mind Control", dict: "rcmbarry", anim: "mind_control_b_loop", flag: 1 },
    { category: "emotes", id: "mindcontrol2", label: "Mind Control 2", dict: "rcmbarry", anim: "bar_1_attack_idle_aln", flag: 1 },
    { category: "emotes", id: "mindcontrol3", label: "Mind Control 3", dict: "rcmbarry", anim: "bar_1_attack_idle_aln", flag: 49 },
    { category: "emotes", id: "clown", label: "Clown", dict: "rcm_barry2", anim: "clown_idle_0", flag: 0 },
    { category: "emotes", id: "clown2", label: "Clown 2", dict: "rcm_barry2", anim: "clown_idle_1", flag: 0 },
    { category: "emotes", id: "clown3", label: "Clown 3", dict: "rcm_barry2", anim: "clown_idle_2", flag: 0 },
    { category: "emotes", id: "clown4", label: "Clown 4", dict: "rcm_barry2", anim: "clown_idle_3", flag: 0 },
    { category: "emotes", id: "clown5", label: "Clown 5", dict: "rcm_barry2", anim: "clown_idle_6", flag: 0 },
    { category: "emotes", id: "tryclothes", label: "Try Clothes", dict: "mp_clothing@female@trousers", anim: "try_trousers_neutral_a", flag: 0 },
    { category: "emotes", id: "tryclothes2", label: "Try Clothes 2", dict: "mp_clothing@female@shirt", anim: "try_shirt_positive_a", flag: 0 },
    { category: "emotes", id: "tryclothes3", label: "Try Clothes 3", dict: "mp_clothing@female@shoes", anim: "try_shoes_positive_a", flag: 0 },
    { category: "emotes", id: "nervous2", label: "Nervous 2", dict: "mp_missheist_countrybank@nervous", anim: "nervous_idle", flag: 49 },
    { category: "emotes", id: "nervous", label: "Nervous", dict: "amb@world_human_bum_standing@twitchy@idle_a", anim: "idle_c", flag: 49 },
    { category: "emotes", id: "nervous3", label: "Nervous 3", dict: "rcmme_tracey1", anim: "nervous_loop", flag: 0 },
    { category: "emotes", id: "namaste", label: "Namaste", dict: "timetable@amanda@ig_4", anim: "ig_4_base", flag: 50 },
    { category: "emotes", id: "dj", label: "DJ", dict: "anim@amb@nightclub@djs@dixon@", anim: "dixn_dance_cntr_open_dix", flag: 1 },
    { category: "emotes", id: "threaten", label: "Threaten", dict: "random@atmrobberygen", anim: "b_atm_mugging", flag: 49 },
    { category: "emotes", id: "radio", label: "Radio", dict: "random@arrests", anim: "generic_radio_chatter", flag: 48 },
    { category: "emotes", id: "rabbit", label: "Rabbit", dict: "random@peyote@rabbit", anim: "wakeup", flag: 1 },
    { category: "emotes", id: "spiderman", label: "Spiderman", dict: "missexile3", anim: "ex03_train_roof_idle", flag: 1 },
    { category: "emotes", id: "boi", label: "Boi", dict: "special_ped@jane@monologue_5@monologue_5c", anim: "brotheradrianhasshown_2", flag: 0 },
    { category: "emotes", id: "adjust", label: "Adjust", dict: "missmic4", anim: "michael_tux_fidget", flag: 48 },
    { category: "emotes", id: "handsup", label: "Hands Up", dict: "missminuteman_1ig_2", anim: "handsup_base", flag: 49 },
    { category: "emotes", id: "pee", label: "Pee", dict: "misscarsteal2peeing", anim: "peeing_loop", flag: 1 },
    { category: "emotes", id: "mindblown", label: "Mind Blown", dict: "anim@mp_player_intcelebrationmale@mind_blown", anim: "mind_blown", flag: 0 },
    { category: "emotes", id: "mindblown2", label: "Mind Blown 2", dict: "anim@mp_player_intcelebrationfemale@mind_blown", anim: "mind_blown", flag: 62 },
    { category: "emotes", id: "boxing", label: "Boxing", dict: "anim@mp_player_intcelebrationmale@shadow_boxing", anim: "shadow_boxing", flag: 1 },
    { category: "emotes", id: "boxing2", label: "Boxing 2", dict: "anim@mp_player_intcelebrationfemale@shadow_boxing", anim: "shadow_boxing", flag: 1 },
    { category: "emotes", id: "stink", label: "Stink", dict: "anim@mp_player_intcelebrationfemale@stinker", anim: "stinker", flag: 48 },
    { category: "emotes", id: "think4", label: "Think 4", dict: "anim@amb@casino@hangout@ped_male@stand@02b@idles", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "adjusttie", label: "Adjust Tie", dict: "clothingtie", anim: "try_tie_positive_a", flag: 0 },
    { category: "emotes", id: "sweep", label: "Sweep", dict: "amb@world_human_janitor@male@idle_a", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "peeposhy", label: "Peepo Shy", dict: "nikez@peepo", anim: "shy", flag: 49 },
    { category: "emotes", id: "orangejustice", label: "Orange Justice", dict: "div@justice@new", anim: "orangejustice", flag: 1 },
    { category: "emotes", id: "floss", label: "Floss", dict: "divined@fndances@new", anim: "dbdance12", flag: 1 },
    { category: "emotes", id: "crabdance", label: "Crab Dance", dict: "divined@fndances@new", anim: "dbdance8", flag: 1 },
    { category: "emotes", id: "cheerleaderdance", label: "Cheerleader Dance", dict: "divined@fndances@new", anim: "dbdance7", flag: 1 },
    { category: "emotes", id: "loser", label: "Loser", dict: "nikez@taunts@loser", anim: "loser", flag: 54 },
    { category: "emotes", id: "sheesh", label: "Sheesh", dict: "clear@custom_anim", anim: "sheesh_clip", flag: 48 },
    { category: "emotes", id: "animerun", label: "Anime Run", dict: "nikez@anime", anim: "run", flag: 49 },
    { category: "emotes", id: "pumping", label: "Pumping", dict: "pumping@custom_anim@pumping", anim: "pumping", flag: 1 },
    { category: "emotes", id: "leginjury", label: "Leg Injury", dict: "yoinks@injury@leg", anim: "yoinks_injury_leg_clip", flag: 1 },
    { category: "emotes", id: "rock", label: "Rock", dict: "yoinks@rps@rock", anim: "yoinks_rps_rock_clip", flag: 54 },
    { category: "emotes", id: "paper", label: "Paper", dict: "yoinks@rps@paper", anim: "yoinks_rps_paper_clip", flag: 54 },
    { category: "emotes", id: "scissors", label: "Scissors", dict: "yoinks@rps@scissors", anim: "yoinks_rps_scissors_clip", flag: 54 },
    { category: "emotes", id: "strum", label: "Strum", dict: "amb@world_human_musician@guitar@male@idle_a", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "drum", label: "Drum", dict: "anim@mp_player_intincarair_drumsbodhi@ds@", anim: "idle_a", flag: 49 },
    { category: "emotes", id: "piano", label: "Piano", dict: "piano@clear@custom_anim", anim: "piano", flag: 49 },
    { category: "emotes", id: "squat", label: "Squat", dict: "squat@nikez", anim: "squat_clip", flag: 2 },
    { category: "emotes", id: "opa", label: "Opa", dict: "yoinks@opa", anim: "custom_clip", flag: 1 },
    { category: "emotes", id: "griddy", label: "Griddy", dict: "yoinks@griddy", anim: "griddy_clip", flag: 47 },
    { category: "emotes", id: "pixelcards", label: "Pixel Cards", dict: "yoinks@yugioh", anim: "yoinks_clip", flag: 49 },
    { category: "emotes", id: "makeitrain", label: "Make It Rain", dict: "anim@mp_player_intupperraining_cash", anim: "idle_a", flag: 49, prop: "wadofbills" },
]