globalThis.EXPRESSIONS = [
    { category: "expressions", label: "Angry", value: "mood_angry_1" },
    { category: "expressions", label: "Drunk", value: "mood_drunk_1" },
    { category: "expressions", label: "Dumb", value: "pose_injured_1" },
    { category: "expressions", label: "Electrocuted", value: "electrocuted_1" },
    { category: "expressions", label: "Grumpy", value: "mood_drivefast_1" },
    { category: "expressions", label: "Happy", value: "mood_happy_1" },
    { category: "expressions", label: "Injured", value: "mood_injured_1" },
    { category: "expressions", label: "Joyful", value: "mood_dancing_low_1" },
    { category: "expressions", label: "Mouthbreather", value: "smoking_hold_1" },
    { category: "expressions", label: "Normal", value: "default" },
    { category: "expressions", label: "One Eye", value: "pose_aiming_1" },
    { category: "expressions", label: "Shocked", value: "shocked_1" },
    { category: "expressions", label: "Sleeping", value: "dead_1" },
    { category: "expressions", label: "Smug", value: "mood_smug_1" },
    { category: "expressions", label: "Speculative", value: "mood_aiming_1" },
    { category: "expressions", label: "Stressed", value: "mood_stressed_1" },
    { category: "expressions", label: "Sulking", value: "mood_sulk_1" },
    { category: "expressions", label: "Weird", value: "effort_2" },
    { category: "expressions", label: "Weird 2", value: "effort_3" },
]