globalThis.PLACED = [
    { category: "placed", id: "chair", label: "Chair (Placed)", dict: "anim@amb@nightclub@peds@", anim: "amb_prop_human_seat_chair_male_generic_base", flag: 1, duration: -1 },
    { category: "placed", id: "sit", label: "Sit (Placed)", dict: "anim@amb@business@bgen@bgen_no_work@", anim: "sit_phone_phoneputdown_idle_nowork", flag: 1 },
    { category: "placed", id: "sit2", label: "Sit 2 (Placed)", dict: "rcm_barry3", anim: "barry_3_sit_loop", flag: 1 },
    { category: "placed", id: "sit3", label: "Sit 3 (Placed)", dict: "amb@world_human_picnic@male@idle_a", anim: "idle_a", flag: 1 },
    { category: "placed", id: "sit4", label: "Sit 4 (Placed)", dict: "amb@world_human_picnic@female@idle_a", anim: "idle_a", flag: 1 },
    { category: "placed", id: "sit5", label: "Sit 5 (Placed)", dict: "anim@heists@fleeca_bank@ig_7_jetski_owner", anim: "owner_idle", flag: 1 },
    { category: "placed", id: "sit6", label: "Sit 6 (Placed)", dict: "timetable@jimmy@mics3_ig_15@", anim: "idle_a_jimmy", flag: 1 },
    { category: "placed", id: "sit7", label: "Sit 7 (Placed)", dict: "anim@amb@nightclub@lazlow@lo_alone@", anim: "lowalone_base_laz", flag: 1 },
    { category: "placed", id: "sit8", label: "Sit 8 (Placed)", dict: "timetable@jimmy@mics3_ig_15@", anim: "mics3_15_base_jimmy", flag: 1 },
    { category: "placed", id: "sit9", label: "Sit 9 (Placed)", dict: "amb@world_human_stupor@male@idle_a", anim: "idle_a", flag: 1 },
    { category: "placed", id: "sitlean", label: "Sit Lean (Placed)", dict: "timetable@tracy@ig_14@", anim: "ig_14_base_tracy", flag: 1 },
    { category: "placed", id: "sitsad", label: "Sit Sad (Placed)", dict: "anim@amb@business@bgen@bgen_no_work@", anim: "sit_phone_phoneputdown_sleeping-noworkfemale", flag: 1 },
    { category: "placed", id: "sitscared", label: "Sit Scared (Placed)", dict: "anim@heists@ornate_bank@hostages@hit", anim: "hit_loop_ped_b", flag: 1 },
    { category: "placed", id: "sitscared2", label: "Sit Scared 2 (Placed)", dict: "anim@heists@ornate_bank@hostages@ped_c@", anim: "flinch_loop", flag: 1 },
    { category: "placed", id: "sitscared3", label: "Sit Scared 3 (Placed)", dict: "anim@heists@ornate_bank@hostages@ped_e@", anim: "flinch_loop", flag: 1 },
    { category: "placed", id: "sitdrunk", label: "Sit Drunk (Placed)", dict: "timetable@amanda@drunk@base", anim: "base", flag: 1 },
    { category: "placed", id: "sitchair2", label: "Sit Chair 2 (Placed)", dict: "timetable@ron@ig_5_p3", anim: "ig_5_p3_base", flag: 1 },
    { category: "placed", id: "sitchair3", label: "Sit Chair 3 (Placed)", dict: "timetable@reunited@ig_10", anim: "base_amanda", flag: 1 },
    { category: "placed", id: "sitchair4", label: "Sit Chair 4 (Placed)", dict: "timetable@ron@ig_3_couch", anim: "base", flag: 1 },
    { category: "placed", id: "sitchair5", label: "Sit Chair 5 (Placed)", dict: "timetable@jimmy@mics3_ig_15@", anim: "mics3_15_base_tracy", flag: 1 },
    { category: "placed", id: "sitchair6", label: "Sit Chair 6 (Placed)", dict: "timetable@maid@couch@", anim: "base", flag: 1 },
    { category: "placed", id: "sitchairside", label: "Sit Chair Side", dict: "timetable@ron@ron_ig_2_alt1", anim: "ig_2_alt1_base", flag: 1 },
]