globalThis.CHAIRS = [
    //BENCH
    {
        prop: 'prop_picnictable_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_picnictable_02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_bench_01a',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_bench_01b',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_bench_01c',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_bench_02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_bench_03',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_bench_04',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_bench_05',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_bench_06',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_bench_08',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_bench_09',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_bench_10',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_bench_11',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'gabz_lamesapd_cellbench',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_fib_3b_bench',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_ld_bench01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_wait_bench_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },

    //CHAIRS
    {
        prop: 'v_res_fa_chair01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.68,
        forwardOffset: 0.07,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_fa_chair02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.07,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_m_dinechair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_club_stagechair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_fh_barcchair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_fh_dineeamesa',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.1,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_fh_dineeamesb',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.1,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_fh_dineeamesc',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.1,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_fh_easychair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.1,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_fh_kitnstool',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.1,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_fh_singleseat',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.1,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_jarmchair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_j_dinechair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_j_stool',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_d_highchair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: -0.05,
        leftOffset: 0.0,
        headingOffset: -180.0,
    },
    {
        prop: 'v_res_m_dinechair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: -0.05,
        leftOffset: 0.0,
        headingOffset: -180.0,
    },
    {
        prop: 'v_res_study_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: -0.05,
        leftOffset: 0.0,
        headingOffset: -180.0,
    },
    {
        prop: 'v_res_trev_framechair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: -0.05,
        leftOffset: 0.0,
        headingOffset: -180.0,
    },
    {
        prop: 'v_res_tre_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: -0.05,
        leftOffset: 0.0,
        headingOffset: -180.0,
    },
    {
        prop: 'v_res_tre_officechair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: -0.05,
        leftOffset: 0.0,
        headingOffset: -180.0,
    },
    {
        prop: 'v_res_tre_stool',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.9,
        forwardOffset: 0.15,
        leftOffset: 0.0,
        headingOffset: -180.0,
    },
    {
        prop: 'v_res_tre_stool_leather',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.9,
        forwardOffset: 0.15,
        leftOffset: 0.0,
        headingOffset: -180.0,
    },
    {
        prop: 'v_res_tre_stool_scuz',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.9,
        forwardOffset: 0.15,
        leftOffset: 0.0,
        headingOffset: -180.0,
    },
    {
        prop: 'v_med_p_easychair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.68,
        forwardOffset: 0.07,
        leftOffset: 0.0,
    },
    {
        prop: 'v_med_whickerchair1',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_yacht_lounger',
        scenario: 'PROP_HUMAN_SEAT_SUNLOUNGER',
        verticalOffset: -0.5,
        forwardOffset: 0.35,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ret_chair_white',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ret_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ret_ta_stool',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'xm_lab_chairarm_26',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'bkr_prop_weed_chair_01a',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_din_chair_04',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_din_chair_08',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_din_chair_09',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_din_chair_12',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_din_stool_04',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.15,
        forwardOffset: 0.12,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairarm_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairarm_03',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairarm_09',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairarm_11',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairarm_12',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairarm_13',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairarm_23',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairarm_24',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairarm_25',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairarm_26',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairstool_12',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairstrip_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairstrip_02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairstrip_03',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairstrip_04',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairstrip_05',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairstrip_06',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairstrip_07',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'apa_mp_h_stn_chairstrip_08',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_patio_lounger_2',
        scenario: 'PROP_HUMAN_SEAT_SUNLOUNGER',
        verticalOffset: -0.6,
        forwardOffset: 0.2,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_patio_lounger_3',
        scenario: 'PROP_HUMAN_SEAT_SUNLOUNGER',
        verticalOffset: -0.6,
        forwardOffset: 0.2,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_patio_lounger1',
        scenario: 'PROP_HUMAN_SEAT_SUNLOUNGER',
        verticalOffset: -0.6,
        forwardOffset: -0.2,
        leftOffset: 0.0,
    },
    {
        prop: 'gr_dlc_gr_yacht_props_lounger',
        scenario: 'PROP_HUMAN_SEAT_SUNLOUNGER',
        verticalOffset: -0.5,
        forwardOffset: 0.33,
        leftOffset: 0.0,
    },
    {
        prop: 'p_patio_lounger1_s',
        scenario: 'PROP_HUMAN_SEAT_SUNLOUNGER',
        verticalOffset: -0.6,
        forwardOffset: -0.2,
        leftOffset: 0.0,
    },
    {
        prop: 'np_fx_sit_anywhere',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.92,
        forwardOffset: 0.08,
        leftOffset: 0.0,
        headingOffset: -90.0,
    },
    {
        prop: 'np_fx_lounge_anywhere',
        scenario: 'PROP_HUMAN_SEAT_SUNLOUNGER',
        verticalOffset: -0.96,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: -90.0,
    },
    {
        prop: 'v_serv_ct_chair02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'hei_prop_heist_off_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'hei_prop_hei_skid_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.92,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chair_01a',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chair_01b',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chair_02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chair_03',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chair_04a',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.11,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chair_04b',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chair_05',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chair_06',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chair_05',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chair_08',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chair_09',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chair_10',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_chateau_chair_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_clown_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_cs_office_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.1,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_direct_chair_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.82,
        forwardOffset: 0.1,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_direct_chair_02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.8,
        forwardOffset: 0.1,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_gc_chair02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_off_chair_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_off_chair_03',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_off_chair_04',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_off_chair_04b',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_off_chair_04_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_off_chair_05',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_old_deck_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.15,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_old_wood_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_rock_chair_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.85,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_skid_chair_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_skid_chair_02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.85,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_skid_chair_03',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.85,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_sol_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_wheelchair_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.92,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_wheelchair_01_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.42,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'p_armchair_01_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'p_clb_officechair_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'p_dinechair_01_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'p_ilev_p_easychair_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'p_soloffchair_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'p_yacht_chair_01_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_club_officechair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_corp_bk_chair3',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.08,
        leftOffset: 0.0,
    },
    {
        prop: 'v_corp_cd_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.09,
        leftOffset: 0.0,
    },
    {
        prop: 'v_corp_offchair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_chair02_ped',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_hd_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_p_easychair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ret_gc_chair03',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.25,
        forwardOffset: -0.05,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_ld_farm_chair01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_table_04_chr',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_table_05_chr',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_table_06_chr',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_leath_chr',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_table_01_chr_a',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 0.08,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_table_01_chr_b',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.97,
        forwardOffset: 0.1,
        leftOffset: 0.01,
        headingOffset: -90.0,
    },
    {
        prop: 'prop_table_02_chr',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.08,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_table_03b_chr',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_table_03_chr',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_torture_ch_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.9,
        forwardOffset: -0.05,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_fh_dineeamesa',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_fh_kitchenstool',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_tort_stool',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_fh_kitchenstool',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_fh_kitchenstool',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_fh_kitchenstool',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_fh_kitchenstool',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    //SEAT
    {
        prop: 'hei_prop_yah_seat_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'hei_prop_yah_seat_02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'hei_prop_yah_seat_03',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_waiting_seat_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_yacht_seat_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_yacht_seat_02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_yacht_seat_03',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.36,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_hobo_seat_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.65,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    //COUCH
    {
        prop: 'prop_rub_couch01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'miss_rub_couch_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_ld_farm_couch01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_ld_farm_couch02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_rub_couch02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_rub_couch03',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_rub_couch04',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    //SOFA
    {
        prop: 'p_lev_sofa_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'p_res_sofa_l_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'p_v_med_p_sofa_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'p_yacht_sofa_01_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_ilev_m_sofa',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_res_tre_sofa_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_tre_sofa_mess_a_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_tre_sofa_mess_b_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'v_tre_sofa_mess_c_s',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    //MISC
    {
        prop: 'prop_roller_car_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'prop_roller_car_02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'ex_prop_offchair_exec_04',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'ba_prop_battle_club_chair_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.1,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'ba_prop_int_glam_stool',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.3,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'np_town_hall_judge_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'vw_prop_vw_offchair_02',
        scenario: 'PROP_HUMAN_SEAT_ARMCHAIR',
        scenarioExit: 'sit_exit_left',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'vw_prop_casino_chair_01a',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        scenarioExit: 'sit_exit_left',
        verticalOffset: -0.25,
        forwardOffset: -0.1,
        leftOffset: 0.0,
        headingOffset: 0.0,
    },
    {
        prop: 'v_res_mbchair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.02,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'V_Res_M_L_Chair1', // dining room chairs winery
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        scenarioExit: 'sit_exit_left',
        verticalOffset: -0.5,
        forwardOffset: -0.05,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'V_Ret_Chair', // upstairs office chairs winery
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: -0.05,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'V_Ret_GC_Chair01', // shitty chairs upstairs winery
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.6,
        forwardOffset: 0.11,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'V_Ret_GC_Chair02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.95,
        forwardOffset: 0.11,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'ba_Prop_Battle_Club_Chair_02', // big office chair winery
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.1,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'V_Res_M_ArmChair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: -0.05,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: -105886377,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.3,
        forwardOffset: 0.1,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 757888276,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.1,
        leftOffset: 0.0,
        headingOffset: 0.0,
    },
    {
        prop: -425962029,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: -0.25,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 1630899471,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.1,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: -523951410,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.1,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: -1786424499,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: -0.1,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: -2065455377,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 1.0,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: -992735415,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.2,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: -1120527678,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.2,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 90.0,
    },
    {
        prop: 'v_serv_ct_chair01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 0.325,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 520143535,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 90.0,
    },
    {
        prop: -1626066319,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.25,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: -470815620,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.15,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: `gr_prop_gr_chair02_ped`,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: `bkr_prop_clubhouse_chair_01`,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'np_mp_h_din_chair_09',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.2,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'prop_bar_stool_01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.2,
        forwardOffset: 0.2,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: -1278649385,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.1,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'v_med_p_deskchair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'gabz_pdprops_chair02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.1,
        leftOffset: 0.0,
    },
    {
        prop: 'np_black_simple_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.0,
        leftOffset: 0.0,
    },
    {
        prop: 'xee_news_cinema_seat_1',
        scenario: 'PROP_HUMAN_SEAT_DECKCHAIR',
        verticalOffset: -1.1,
        forwardOffset: -0.2,
        leftOffset: 0.1,
    },
    {
        prop: 'xee_news_cinema_seat_2',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.1,
        forwardOffset: -0.2,
        leftOffset: 0.1,
    },
    {
        prop: 'xee_news_cinema_seat_3',
        scenario: 'PROP_HUMAN_SEAT_DECKCHAIR',
        verticalOffset: -1.1,
        forwardOffset: -0.2,
        leftOffset: 0.1,
    },
    {
        prop: -2139482741,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.25,
        forwardOffset: -0.1,
        leftOffset: 0.0,
        headingOffset: 0.0,
    },
    {
        prop: -1470542885,
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.95,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'll_bar_stool',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.65,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'll_meetingroom_chair',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.53,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'v_corp_bk_chair2',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -1.0,
        forwardOffset: 0.1,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'gabz_pdprops_chair01',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 180.0,
    },
    {
        prop: 'sf_prop_sf_bench_piano_01a_np',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: 0.0,
    },
    {
        prop: 'sf_prop_sf_chair_stool_08a_np',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.0,
        leftOffset: 0.0,
        headingOffset: -90.0,
    },
    {
        prop: 'xm_base_cia_chair_conf',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: -0.1,
        leftOffset: 0.05,
        headingOffset: -180.0,
    },
    {
        prop: 'sm_op_prop_chair_002',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0,
        leftOffset: 0.05,
        headingOffset: -180.0,
    },
    {
        prop: 'sm_op_prop_off_chair_001',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.05,
        leftOffset: 0.05,
        headingOffset: -180.0,
    },
    {
        prop: 'sm_op_prop_armchair_001',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.05,
        leftOffset: 0.05,
        headingOffset: -180.0,
    },
    {
        prop: 'hane_bc_sheriff_wood_chair_b',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.5,
        forwardOffset: 0.05,
        leftOffset: 0.05,
        headingOffset: -180.0,
    },
    {
        prop: 'hane_bc_sheriff_off_chair_a',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.0,
        leftOffset: 0.05,
        headingOffset: -180.0,
    },
    {
        prop: 'lab_chr',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.25,
        forwardOffset: 0.1,
        leftOffset: 0.05,
        headingOffset: -180.0,
    },
    {
        prop: 'hn_h_stn_chairarm_02',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: -0.325,
        leftOffset: 0.05,
        headingOffset: -180.0,
    },
    {
        prop: 'hn_bcmed_chair_b',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.05,
        leftOffset: 0.05,
        headingOffset: -180.0,
    },
    {
        prop: 'sm_op_prop_chair_001',
        scenario: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
        verticalOffset: -0.45,
        forwardOffset: 0.05,
        leftOffset: 0.05,
        headingOffset: -180.0,
    },
    {
        prop: 'prop_ld_toilet_01',
        scenario: 'PROP_HUMAN_SEAT_ARMCHAIR',
        verticalOffset: -0.875,
        forwardOffset: 0.0,
        leftOffset: 0,
        headingOffset: -180.0,
    },
];
