globalThis.WALKS = [
    { category: "walks", label: "Arrogant", value: "move_f@arrogant@a" },
    { category: "walks", label: "Casual", value: "move_m@casual@a" },
    { category: "walks", label: "Casual 2", value: "move_m@casual@b" },
    { category: "walks", label: "Casual 3", value: "move_m@casual@c" },
    { category: "walks", label: "Casual 4", value: "move_m@casual@d" },
    { category: "walks", label: "Casual 5", value: "move_m@casual@e" },
    { category: "walks", label: "Casual 6", value: "move_m@casual@f" },
    { category: "walks", label: "Confident", value: "move_m@confident" },
    { category: "walks", label: "Business", value: "move_m@business@a" },
    { category: "walks", label: "Business 2", value: "move_m@business@b" },
    { category: "walks", label: "Business 3", value: "move_m@business@c" },
    { category: "walks", label: "Femme", value: "move_f@femme@" },
    { category: "walks", label: "Gangster", value: "move_m@gangster@generic" },
    { category: "walks", label: "Gangster 2", value: "move_m@gangster@ng" },
    { category: "walks", label: "Gangster 3", value: "move_m@gangster@var_e" },
    { category: "walks", label: "Gangster 4", value: "move_m@gangster@var_f" },
    { category: "walks", label: "Gangster 5", value: "move_m@gangster@var_i" },
    { category: "walks", label: "Heels", value: "move_f@heels@c" },
    { category: "walks", label: "Heels 2", value: "move_f@heels@d" },
    { category: "walks", label: "Hiking", value: "move_m@muscle@a" },
    { category: "walks", label: "Quick", value: "move_m@quick" },
    { category: "walks", label: "Wide", value: "move_m@bag" },
    { category: "walks", label: "Scared", value: "move_f@scared" },
    { category: "walks", label: "Brave", value: "move_m@brave" },
    { category: "walks", label: "Tipsy", value: "move_m@drunk@slightlydrunk" },
    { category: "walks", label: "Injured", value: "move_m@injured" },
    { category: "walks", label: "Tough", value: "move_m@tough_guy@" },
    { category: "walks", label: "Sassy", value: "move_m@sassy" },
    { category: "walks", label: "Sad", value: "move_m@sad@a" },
    { category: "walks", label: "Posh", value: "move_m@posh@" },
    { category: "walks", label: "Alien", value: "move_m@alien" },
    { category: "walks", label: "Nonchalant", value: "move_m@non_chalant" },
    { category: "walks", label: "Hobo", value: "move_m@hobo@a" },
    { category: "walks", label: "Money", value: "move_m@money" },
    { category: "walks", label: "Swagger", value: "move_m@swagger" },
    { category: "walks", label: "Man Eater", value: "move_f@maneater" },
    { category: "walks", label: "ChiChi", value: "move_f@chichi" },
    { category: "walks", label: "Chubby", value: "move_chubby" },
    { category: "walks", label: "Armored", value: "anim_group_move_ballistic" },
    { category: "walks", label: "Wider", value: "move_characters@franklin@fire" },
    { category: "walks", label: "Widest", value: "move_characters@michael@fire" },
    { category: "walks", label: "Widester", value: "move_m@fire" },
    { category: "walks", label: "Franklin", value: "move_p_m_one" },
    { category: "walks", label: "Janitor", value: "move_p_m_zero_janitor" },
    { category: "walks", label: "Janitor Slow", value: "move_p_m_zero_slow" },
    { category: "walks", label: "Lester", value: "move_heist_lester" },
    { category: "walks", label: "Michael", value: "move_ped_bucket" },
    { category: "walks", label: "Sassy 2", value: "move_f@sassy" },
    { category: "walks", label: "Trevor", value: "move_p_m_two" },
    { category: "walks", label: "Default", value: "default" },
]