fx_version 'adamant'
games { 'gta5' }

author 'Razed'
description 'nopixel 4.0 - World Overhaul'
version '1.0.0'

this_is_a_map 'yes'

data_file 'DLC_ITYP_REQUEST' 'stream/airport_metadata_005_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/cityhills_01_metadata_001_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/cityhills_01_metadata_004_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/cityhills_01_metadata_005_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/cityhills_03_metadata_001_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_01_metadata_006_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_02_metadata_005_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_03_metadata_001_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_03_metadata_009_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_001_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_008_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/downtown_01_metadata_005.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/downtown_01_metadata_006.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/downtown_01_metadata_007.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/downtown_01_metadata_007_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/downtown_01_metadata_009_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/downtown_01_metadata_010_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/downtown_01_metadata_013_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/downtown_01_metadata_014_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/dt1_lod.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/dt1_rd1_interior_dt1_rd1_tun3.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/hollywood_metadata_006_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/hollywood_metadata_010_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/indust_02_metadata_001_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/int_club.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/int_medical.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/kt1_04_interior_kt1_04_roadtunnel_int.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/lev_des.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sm_20_interior_sm20_tun1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sm_20_interior_sm20_tun2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sm_20_interior_sm20_tun3.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sm_20_interior_sm20_tun4.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_bush.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_cacti.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_fanpalm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_int_4.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_int_19.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_int_36.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_int_39.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_int_44.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_int_68.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_int_metro_subway1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_minigame.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_palm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_snow.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_sports.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_trees.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/wthr_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/wthr_props_rain.ytyp'