Citizen.CreateThread(function()
	AddTextEntryByHash(0x6375F673, "V-450")
    AddTextEntryByHash(0x05D97D55, "Stanier")
	AddTextEntryByHash(0x06089F0B, "Scout")
	AddTextEntryByHash(0xA0D4D4A9, "Oracle")
	AddTextEntryByHash(0xD2719516, "Novak")
	AddTextEntryByHash(0xE21C346F, "Speedo")
	AddTextEntryByHash(0xBF776F26, "Schafter V12")
	AddTextEntryByHash(0x070E2192, "Baller")
	AddTextEntryByHash(0xA9DA270B, "Stanier")
	AddTextEntryByHash(0x80CD148E, "Stanier")
	AddTextEntryByHash(0xADB8CBA9, "Buffalo S")
	AddTextEntryByHash(0x85591DB2, "Torrence")
	AddTextEntryByHash(0x0EFBE06C, "Torrence")

    AddTextEntryByHash(`POLBUFFALO4`, "Buffalo STX Police")
    AddTextEntryByHash(`POLCARACARA`, "Caracara Police")
    AddTextEntryByHash(`POLCOMET`, "Comet S2 Police")
    AddTextEntryByHash(`POLCOQ4`, "Coquette D10 Police")
    AddTextEntryByHash(`POLDOM`, "Dominator GTX")
    AddTextEntryByHash(`POLSCOUT2`, "Scout Police 2020")
    AddTextEntryByHash(`POLVIGERO2`, "Vigero ZX Police")
    AddTextEntryByHash(`POLVSTR`, "V-STR Police")

	AddTextEntryByHash(`POLICE_ANTENNA`, "Antenna")
	AddTextEntryByHash(`POLICE_DIVIDER`, "Divider")
	AddTextEntryByHash(`CALLSIGN_L`, "Left CallSign")
	AddTextEntryByHash(`CALLSIGN_C`, "Center CallSign")
	AddTextEntryByHash(`CALLSIGN_R`, "Right CallSign")
	AddTextEntryByHash(`CALLSIGN_A0`, "0")
	AddTextEntryByHash(`CALLSIGN_A1`, "1")
	AddTextEntryByHash(`CALLSIGN_A2`, "2")
	AddTextEntryByHash(`CALLSIGN_A3`, "3")
	AddTextEntryByHash(`CALLSIGN_A4`, "4")
	AddTextEntryByHash(`CALLSIGN_A5`, "5")
	AddTextEntryByHash(`CALLSIGN_A6`, "6")
	AddTextEntryByHash(`CALLSIGN_A7`, "7")
	AddTextEntryByHash(`CALLSIGN_A8`, "8")
	AddTextEntryByHash(`CALLSIGN_A9`, "9")
	AddTextEntryByHash(`CALLSIGN_B0`, "0")
	AddTextEntryByHash(`CALLSIGN_B1`, "1")
	AddTextEntryByHash(`CALLSIGN_B2`, "2")
	AddTextEntryByHash(`CALLSIGN_B3`, "3")
	AddTextEntryByHash(`CALLSIGN_B4`, "4")
	AddTextEntryByHash(`CALLSIGN_B5`, "5")
	AddTextEntryByHash(`CALLSIGN_B6`, "6")
	AddTextEntryByHash(`CALLSIGN_B7`, "7")
	AddTextEntryByHash(`CALLSIGN_B8`, "8")
	AddTextEntryByHash(`CALLSIGN_B9`, "9")
	AddTextEntryByHash(`CALLSIGN_C0`, "0")
	AddTextEntryByHash(`CALLSIGN_C1`, "1")
	AddTextEntryByHash(`CALLSIGN_C2`, "2")
	AddTextEntryByHash(`CALLSIGN_C3`, "3")
	AddTextEntryByHash(`CALLSIGN_C4`, "4")
	AddTextEntryByHash(`CALLSIGN_C5`, "5")
	AddTextEntryByHash(`CALLSIGN_C6`, "6")
	AddTextEntryByHash(`CALLSIGN_C7`, "7")
	AddTextEntryByHash(`CALLSIGN_C8`, "8")
	AddTextEntryByHash(`CALLSIGN_C9`, "9")
	AddTextEntryByHash(`LSPD_LIV`, "LSPD Livery")
	AddTextEntryByHash(`SHERIFF_LIV`, "Sheriff Livery")
	AddTextEntryByHash(`HP_LIV`, "Highway Patrol Livery")
end)